caras/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('faceApp/', include('faceApp.urls')),
    
]

faceApp/urls.py
from django.urls  import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name= "faceApp"

urlpatterns=[
    path("", views.index, name="index"),
    path("face/", views.index, name="face"),
    path("upload/", views.upload, name="upload"),
    path("manage_upload/", views.manage_upload, name="manage_upload"),
    path("show_image/<int:id>", views.show_image, name="show_image"),
    path("<int:iddetalle>/detalle", views.detalle, name="detalle"),
    path("blur_image", views.blur_image, name="blur_image"),
    path("show_blur_image/<str:id>", views.show_blur_image, name="show_blur_image"),
    
]
if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

faceApp/models.py
from django.db import models

# Create your models here.
class GalleryImage(models.Model):
    title = models.CharField(max_length=255)
    image= models.ImageField(upload_to="faceApp/gallery_images")

faceApp/forms.py
from django import forms
from .models import GalleryImage

class GalleryImageForm(forms.ModelForm):
    class Meta: 
        model = GalleryImage
        fields = ["title" , "image"]

faceApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import GalleryImageForm
from .models import GalleryImage
import boto3
from botocore.exceptions import NoCredentialsError
import json
from pathlib import Path
from django.http import JsonResponse
import cv2
import numpy as np
from PIL import Image

def index(request):
    print("index")
    context = {"valor":"texto"}
    return render(request, "faceApp/index.html", context)

def detalle(request, iddetalle):
    return HttpResponse("detalle %s." % iddetalle)

def upload(request):
    print(request)
    form = GalleryImageForm()
    print(form)
    return render(request, "faceApp/upload.html", { "form": form })

def manage_upload(request):
    if request.method == "POST":
        form = GalleryImageForm(request.POST, request.FILES)
        if form.is_valid():
            object=form.save()
            return redirect("faceApp:show_image", id=object.id)
    return redirect("faceApp:index")

def show_image(request, id):    
    aws_access_key_id="ASIAT47P6J6FH3S6NTMU"
    aws_secret_access_key="yenlhoQIcmiJMNwWqWkWTXVwy49v86NL7RxXLhqV"
    aws_session_token="FwoGZXIvYXdzEJv//////////wEaDHPwF1xOYvyamh88cCLAAW3eZNW7Gnz7uEGmDAi0AiWZSex47xdSI/Wqf5aHKNEkMv8uPnEV77mOZp1VS8xuzqngpD4XlhEwZiidkgwUr5/cdjdhqtu5vnbl9J3t37BVaGjWcaP+1MNR8xXcxHq09S79foMjCpgS8Bl+57afqhtAFiKfNI1AW8Ez+qGmrYgHtXbe7zLgFh71vu0g3KA1dUwOWCYBRey3vnUal3O5zQm56WFH1RrsY605RvuycJ+yqjj4r+6TjJdz1+EwjT9smyiz6ZGhBjItxH57s2A0EVTflgB3KWd7J4z32M4h9tWqmhHQckpm7iRfAai3XQvSgSXkc5iy"
    bucket="trulete-iabd-bucket"
    zona="us-east-1"
    imgobject=GalleryImage.objects.get(id = id)
    fullpath = "c:/iabd/pia/django/caras" + imgobject.image.url
    photo = open(fullpath)
    
    def SubeS3(local_file, bucket, s3_file):
        s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,aws_session_token=aws_session_token)
        s3.upload_file(local_file, bucket, s3_file)
    
    SubeS3(fullpath, bucket, 'Reconoce.jpg')
    
    reko = boto3.client('rekognition', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,aws_session_token=aws_session_token, region_name=zona)
    resultado = reko.detect_faces(Image={'S3Object': {'Bucket': bucket, 'Name': 'Reconoce.jpg'}}, Attributes=['ALL'])

    image = cv2.imread(fullpath)

    menores = []
    for i in resultado['FaceDetails']:
        if i['AgeRange']['Low'] <= 18:
            bounding_box = i['BoundingBox']
            left = int(bounding_box['Left'] * image.shape[1])
            top = int(bounding_box['Top'] * image.shape[0])
            width = int(bounding_box['Width'] * image.shape[1])
            height = int(bounding_box['Height'] * image.shape[0])
            # menores.append({left, top, width, height})
            menores.append({'left':left,'top':top,'width':width,'height':height})

    with open("faceApp/static/faceApp/assets/menores.json", "w") as outfile:
        json.dump(menores, outfile)
        outfile.close()

    print(id)
    object=GalleryImage.objects.get(id = id)
    return render(request, "faceApp/show_image.html", { "data": object })

def blur_image(request):

    id = request.POST['imagen']
    coords = request.POST['coordenadas']
    object = GalleryImage.objects.get(id = id)
    
    #img = cv2.imread("c:/iabd/pia/django/caras"+object.image.url)
    img = Image.open("c:/iabd/pia/django/caras"+object.image.url)
    new_file = 'imagen_final.jpg'
    #img_cv2 = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA)
    img_cv2 = cv2.cvtColor(np.array(img), cv2.COLOR_RGB2RGBA)
    for item in json.loads(coords):
        x = int(item[0])
        y = int(item[1])
        w = int(item[2])
        h = int(item[3])
        img_cv2[y : y + h, x : x + w] = cv2.GaussianBlur(img_cv2[y : y + h, x : x + w], (31,31), 0)
    cv2.imwrite('faceApp/static/faceApp/assets/img/'+new_file, img_cv2)
    
    
    
    return redirect("faceApp:show_blur_image",id='imagen_final.jpg')
    #return render(request, "faceApp/show_image_2.html", { "data": object })

def show_blur_image(request,id):
    #object = GalleryImage.objects.get(id = id)
    return render(request, "faceApp/show_image_2.html", { "data": id })

faceApp/templates/faceApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <base href="http://127.0.0.1:8000/faceApp">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DUA: Django Upload App</title>
    <link rel="stylesheet" href="{% static 'faceApp/assets/css/estilo.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'faceApp/assets/img/favicon.png' %}">
    <link rel="stylesheet" href="https://unpkg.com/jcrop/dist/jcrop.css">
    <script src="https://unpkg.com/jcrop"></script>
    {% block estilo_script %}{% endblock %}
</head>
<body>
    <h1> Cargador de imágenes</h1>
    <img src="{% static 'faceApp/assets/img/imagen.jpg' %}" alt="caras" width="300">
    {% block contenido %}{% endblock %}
    <script src=""{}></script>
</body>
</html>

faceApp/templates/faceApp/index.html
{% extends "faceApp/base.html" %}
{% block contenido %}
    <ul>
        <li>
            <a href="{% url 'faceApp:upload' %}">upload</a>
        </li>
    </ul>

{% endblock %}

faceApp/templates/faceApp/show_image.html
{% extends "faceApp/base.html" %}

{% block contenido %}


    <h1>Titulo de la imagen: {{ data.title }}</h1>
    <h3>id de la imagen: {{ data.id }}</h3>
    <h3>ruta de la imagen: {{ data.image.url }}</h3>
    <img src="faceApp{{ data.image.url }}" id="targetimg"/>

    <form id="formu" action="{% url 'faceApp:blur_image' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="coordenadas" id="coordenadas">
        <input type="hidden" name="imagen" value="{{data.id}}">
        <input type="submit" value="Hacer blur">
    </form>

    


    <script>

        fetch('/static/faceApp/assets/menores.json')
            .then(response => response.json())
            .then(data => {
                // Guardar el contenido recuperado en una variable
                console.log(data);
                pintaLosRectagulos(data);
        })
            
        
        const jcrop = Jcrop.attach('targetimg',{
                        multi: true
                      });
        
        function pintaLosRectagulos(data){
            for (let i = 0; i < data.length; i++) {
                var coord = data[i];
                var left = coord.left;
                var top = coord.top;
                var width = coord.width;
                var height = coord.height;
                var rectangulo =Jcrop.Rect.create(left, top, width, height);
                jcrop.newWidget(rectangulo, {});
                console.log('esto es un ',rectangulo);
            }
        }
        
        function getCoordinates() {
            let crops = jcrop.crops;
            let coords = [];
            for (const crop of crops) {
                coords.push([crop.pos.x, crop.pos.y, crop.pos.w, crop.pos.h]);
            }
            return JSON.stringify(coords);
        }
        
        let formulario = document.getElementById('formu');
        let coordenadas = document.getElementById('coordenadas');
            formulario.addEventListener('submit', function() {
                coordenadas.value = getCoordinates();
        });
    
    
    </script>

    


    
{% endblock %}

faceApp/templates/faceApp/show_image_2.html
{% extends "faceApp/base.html" %}
    {% block contenido %}


    <h1>Titulo de la imagen: {{ data }}</h1>
    <img src="static/faceApp/assets/img/imagen_final.jpg" />
    {% endblock %}
    
    

faceApp/templates/faceApp/upload.html
{% extends "faceApp/base.html" %}


{% block contenido %}
    <form method="post" enctype="multipart/form-data" name="upload_data" action="{% url 'faceApp:manage_upload' %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="subir">
    </form>
{% endblock %}